---
title: Moritz Kopp Design
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  main:
    title: Startseite
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: main
  values:
    layout: page
    title: 
    gallery:
    - image: 
      description: 
permalink: pretty
primary_color: "#d20000"
text_font: Molengo
heading_font: Roboto Condensed
description: Moritz Kopp Grafikdesign. Social-Media-und Printdesign, Corporate Design.
  Darunter Flyer, Visitenkarten, YouTube Channeldesign, Facebookdesign.
logo: "/uploads/Website-Icon.png"
banner_image: 
author: Moritz Kopp
street: Unterer Fuchsgraben 29
city: 97318 Kitzingen
mail: moritz@kopp.design
facebook: https://facebook.com
tel: 1234567890
links: 
exclude:
- LICENSE
- README.md
include:
- ".firebaserc"
- firebase.json
plugins:
- jekyll-sass-converter
sass:
  style: compressed
url: https://kopp.design/
baseurl: 