---
title: Moritz Kopp Design
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  startseite:
    title: Startseite
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
primary_color: "#C04848"
description: Hallo
logo: "/uploads/Website-Icon.png"
isolang: de
exclude:
- LICENSE
- README.md
include:
- ".firebaserc"
- firebase.json
plugins:
- jekyll-sass-converter
sass:
  style: compressed
url: https://kopp.design/
baseurl: 
