---
title: Moritz Kopp Design
timezone: Europe/Berlin
collections:
  main:
    title: Startseite
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: main
  values:
    layout: page
    title:
    gallery:
      - src:
        description:
permalink: pretty
primary_color: "#C04848"
text_font: Molengo
heading_font: Crete Round
description: Moritz Kopp Grafikdesign. Social-Media-und Printdesign, Corporate Design.
  Darunter Flyer, Visitenkarten, YouTube Channeldesign, Facebookdesign.
logo: "/uploads/Website-Icon.png"
exclude:
- LICENSE
- README.md
include:
- ".firebaserc"
- firebase.json
plugins:
- jekyll-sass-converter
sass:
  style: compressed
url: https://kopp.design/
baseurl: 