---
title: Moritz Kopp Design
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  main:
    title: Startseite
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: main
  values:
    layout: page
    title: 
    gallery:
    - image: 
      description: 
permalink: pretty
primary_color: "#d20000"
text_font: Molengo
heading_font: Passion One
description: Moritz Kopp Grafikdesign. Social-Media-und Printdesign, Corporate Design.
  Darunter Flyer, Visitenkarten, YouTube Channeldesign, Facebookdesign.
logo: "/uploads/Website-Icon.png"
banner_image:
links:
<<<<<<< HEAD
=======
- link: print
  title: Print
- link: social-media
  title: Social-Media
- link: kontakt
  title: Kontakt
>>>>>>> f1cbb04fc546daea43cba4e4c172ab51a57d6ed3
exclude:
- LICENSE
- README.md
include:
- ".firebaserc"
- firebase.json
plugins:
- jekyll-sass-converter
sass:
  style: compressed
url: https://kopp.design/
baseurl: 
