---
title: Moritz Kopp Design
timezone: Europe/Berlin
collections:
  posts:
    title: Posts
    output: true
  startseite:
    title: Startseite
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
primary_color: "#C04848"
isolang: de
exclude:
- LICENSE
- README.md
include:
- ".firebaserc"
- firebase.json
replacements:
- - "<img"
  - "<amp-img"
- - alt="" />
  - ' layout="responsive" height="300px" width="600px"></amp-img>'
- - "<video"
  - "<amp-video"
- - "</video"
  - "</amp-video"
- - <script src="https://gist.github.com/lukas-h/
  - <amp-gist data-gistid="
- - .js"></script>
  - '" layout="fixed-height" height="250"></amp-gist>'
- - id="amp"
  - id="a-m-p"
plugins:
- jekyll-sass-converter
sass:
  style: compressed
description: Hallo
url: https://kopp.design/
baseurl: 